version: '3.9'

services:
  # Database.
  db:
    image: library/postgres:${DB_POSTGRES_IMAGE_TAG}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_DB}
    volumes:
      - airproject_db:/var/lib/postgresql/airproject_db

  # Air Project service.
  ap:
    image: air-project:${AP_IMAGE_TAG}
    ports:
      - ${AP_PORT}:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${DB_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
  airproject_db:
    external: true
